modLoader="javafml" #mandatory
loaderVersion="[40,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Cave-Biomes/issues"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_full_name}"
    credits="Thanks so much to all my patrons!"
    authors="YUNGNICKYOUNG, SuperCoder79, Sully, LudoCrypt, K.jpg, Frenderman"
    description="${mod_description}"
    logoFile="logo.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-cave-biomes"

[modproperties.${mod_id}]
    catalogueImageIcon="catagloue_icon.png"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.8,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.${mod_id}]]
    modId="yungsapi"
    versionRange="[${mc_version}-Forge-${yungsapi_version},)"
    mandatory=true
    ordering="NONE"
    side="BOTH"

    [[dependencies.${mod_id}]]
    modId="terrablender"
    versionRange="[${terrablender_version},)"
    mandatory=true
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib3"
    versionRange="[${forge_geckolib_version},)"
    mandatory=true
    ordering="NONE"
    side="BOTH"
